# Version.cmake - Parse version from project and expose as definitions
set(SPW_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(SPW_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(SPW_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(SPW_VERSION_STRING "${PROJECT_VERSION}")

add_compile_definitions(
    SPW_VERSION_MAJOR=${SPW_VERSION_MAJOR}
    SPW_VERSION_MINOR=${SPW_VERSION_MINOR}
    SPW_VERSION_PATCH=${SPW_VERSION_PATCH}
    SPW_VERSION_STRING="${SPW_VERSION_STRING}"
)
